services:
  makerprint-api:
    image: ghcr.io/atelier-epita/makerprint-api:latest
    build:
      context: makerprint
      dockerfile: Dockerfile
    
    privileged: true
    container_name: makerprint-api
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./logs:/var/log
      - ./config:/config
      - ./makerprint/makerprint:/app/makerprint
      - /dev:/dev
    command: ["hypercorn", "--bind", "0.0.0.0:5000", "--reload", "makerprint.main:app"]
    environment:
      - GCODEFOLDER=/data
      - LOGPATH=/var/log/makerprint.log
      - LOGLEVEL=DEBUG
      - DEBUG=true
      - DATABASE_PATH=/data/makerprint.db
    networks:
      - makerprint-net

  makerprint-web:
    image: ghcr.io/atelier-epita/makerprint-web:latest
    build:
      context: makerprint-web
      dockerfile: Dockerfile
      target: dev
    environment:
      - VITE_API_URL=/api
      - VITE_SOCKET_URL=/socket
    container_name: makerprint-web
    restart: unless-stopped
    networks:
      - makerprint-net
    volumes:
      - ./makerprint-web/src:/app/src
      - ./makerprint-web/public:/app/public
    command: ["npm", "run", "dev"]
    ports: # for ws debug stuff
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: makerprint-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/private
    depends_on:
      - makerprint-api
      - makerprint-web
    networks:
      - makerprint-net

networks:
  makerprint-net:
    driver: bridge