version: '3.3'

services:
  makerprint-api:
    image: ghcr.io/atelier-epita/makerprint-api:latest
    build:
      context: makerprint
      dockerfile: Dockerfile
    
    container_name: makerprint-api
    restart: unless-stopped
    devices:
      - /dev:/dev
    volumes:
      - ./data:/data
      - ./logs:/var/log
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - GCODEFOLDER=/data
      - LOGPATH=/var/log/makerprint.log
      - LOGLEVEL=DEBUG
    networks:
      - makerprint-net

  makerprint-web:
    image: ghcr.io/atelier-epita/makerprint-web:latest
    build:
      context: makerprint-web
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: /api
    
    container_name: makerprint-web
    restart: unless-stopped
    networks:
      - makerprint-net

  nginx:
    image: nginx:latest
    container_name: makerprint-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/private
    depends_on:
      - makerprint-api
      - makerprint-web
    networks:
      - makerprint-net

networks:
  makerprint-net:
    driver: bridge